---
all:
  children:
    CVP:
      hosts:
        cv_ztp:
          ansible_host: 192.168.0.5
          ansible_user: root
          ansible_password: cvproot
        cv_server:
          ansible_httpapi_host: 192.168.0.5
          ansible_host: 192.168.0.5
          ansible_user: arista
          ansible_password: arista
          ansible_connection: httpapi
          ansible_httpapi_use_ssl: true
          ansible_httpapi_validate_certs: false
          ansible_network_os: eos
          ansible_httpapi_port: 443
          # Configuration to get Virtual Env information
          ansible_python_interpreter: $(which python3)
    # DC1_Fabric - EVPN Fabric running in home lab
    DC1:
      children:
        DC1_FABRIC:
          children:
            DC1_SPINES:
              hosts:
                DC1-SPINE1:
                  ansible_host: 192.168.0.10
                DC1-SPINE2:
                  ansible_host: 192.168.0.11
            DC1_L3LEAFS:
              children:
                DC1_LEAF1:
                  hosts:
                    DC1-LEAF1A:
                      ansible_host: 192.168.0.12
                    DC1-LEAF1B:
                      ansible_host: 192.168.0.13
                DC1_LEAF2:
                  hosts:
                    DC1-LEAF2A:
                      ansible_host: 192.168.0.14
                    DC1-LEAF2B:
                      ansible_host: 192.168.0.15
          vars:
            ansible_connection: httpapi
            ansible_network_os: eos
            ansible_user: ansible
            # should use vault for passwords
            ansible_ssh_pass: ansible
            ansible_become: true
            ansible_become_method: enable
            ansible_httpapi_use_ssl: true
            ansible_httpapi_validate_certs: false
        DC1_TENANTS_NETWORKS:
          children:
            DC1_L3LEAFS:
        DC1_SERVERS:
          children:
            DC1_L3LEAFS:
