---
# Validation lab
# local users
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$x8MtobO1ifPGeY/q$HinQcYplQQjvAueXX4EWNU0J8CfbpuB86aV5tlMlh8zTAXkAYIV/6ETTZf6vT6ElQEGOuSMopNivYfRbc6m7O1"

  arista:
    privilege: 15
    role: network-admin
    sha512_password: "$6$x8MtobO1ifPGeY/q$HinQcYplQQjvAueXX4EWNU0J8CfbpuB86aV5tlMlh8zTAXkAYIV/6ETTZf6vT6ElQEGOuSMopNivYfRbc6m7O1"

# Cloud Vision server information
cvp_instance_ip: 192.168.0.5
cvp_ingestauth_key: 'atd-lab'
# cvp_ingestauth_key: telarista

# OOB Management network default gateway.
mgmt_gateway: 192.168.0.1

# dns servers.
name_servers:
  - 8.8.8.8

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Managment VRF
ntp_servers:
  - 192.168.0.1
