port_profiles:


  TENANT_A_OPZone:
    mode: access
    vlans: "110"

  TENANT_A_ALL:
    mode: trunk
    vlans: "120-130,160-161"

servers:

  server-1:
    rack: RackA
    adapters:
      - server_ports: [ Eth2, Eth3 ]
        switch_ports: [ Ethernet4, Ethernet4 ]
        switches: [ DC1-LEAF2A, DC1-LEAF2B ]
        profile: TENANT_A_ALL
        port_channel:
          state: present
          description: PortChannel example
          mode: active
